### ISSUE TITLE
Storable não funciona com enum

### ISSUE THREAD

**Issue by EduardoRenani** [rodrigowoulddo/didicloud#1]
Se um dos atributos da model for um enum com o rawType igual ao tipo do campo no cloudkit, mesmo assim ele não consegue converter pra CKRecord 

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Objects of class __SwiftValue cannot be set on CKRecordValueStore'

**Comment by rodrigowoulddo** [comment]
a partir do [Release 0.2.0](https://github.com/rodrigowoulddo/didicloud/releases/tag/0.2.0) o protocolo `Storable` possui um parser custom, definido pelo teu próprio projeto. Nesse `Parser`, tu mesmo define como os enums serão inseridos no banco e traduzidos pra enum no app. É sugerido  que o enum herde de `Int`, e os métodos `toRecord` e `from(record: CKRecord)` do parser convertam o enum usando `MyEnum.rawValue` e `MyEnum(int: retrievedInt)`.

**Comment by rodrigowoulddo** [comment]
a partir do [Release 0.2.0](https://github.com/rodrigowoulddo/didicloud/releases/tag/0.2.0) o protocolo `Storable` possui um parser custom, definido pelo teu próprio projeto. Nesse `Parser`, tu mesmo define como os enums serão inseridos no banco e traduzidos pra enum no app. É sugerido  que o enum herde de `Int`, e os métodos `toRecord` e `from(record: CKRecord)` do parser convertam o enum usando `MyEnum.rawValue` e `MyEnum(int: retrievedInt)`.
